import { createSlice } from '@reduxjs/toolkit';
import type { PayloadAction } from '@reduxjs/toolkit';
import type { RootState } from '../../app/store';

export enum TodoPhase {
  pending = 'pending',
  processing = 'processing',
  finished = 'finished',
  canceled = 'canceled',
}

export interface TodoForm {
  title: string;
  content: string;
}

export interface TodoState extends TodoForm {
  id: string;
  phase?: TodoPhase;
  createAt: number; // new Date().getTime()
}

interface TodosState {
  todos: TodoState[];
}

const initialState: TodosState = { todos: [] };

export const todosSlice = createSlice({
  name: ' todos',
  initialState,
  reducers: {
    // reducer should be pure function so it is not suppoed to generated id
    // ideally, the id should be generated by backend
    createOneTodo: (state, action: PayloadAction<TodoState>) => {
      const newTodo = action.payload;
      newTodo.phase = TodoPhase.pending;
      state.todos = [...state.todos, newTodo];
    },
    deleteOneTodo: (state, action: PayloadAction<string>) => {
      state.todos = state.todos.filter((todo) => todo.id !== action.payload);
    },
    deleteAllTodos: (state) => {
      state.todos = [];
    },
  },
});

export const { createOneTodo, deleteOneTodo, deleteAllTodos } =
  todosSlice.actions;

export const selectTodos = (state: RootState) => state.todos.todos;

export default todosSlice.reducer;
