import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import type { PayloadAction } from '@reduxjs/toolkit';
import type { RootState } from '../../store';
import JokeAxiosApi from '../../../axiosApis/joke';
import { v4 as v4uuid } from 'uuid';

export enum TodoPhase {
  pending = 'pending',
  processing = 'processing',
  finished = 'finished',
  canceled = 'canceled',
}

export interface TodoForm {
  title: string;
  content: string;
}

export interface TodoState extends TodoForm {
  id: string;
  phase?: TodoPhase;
  createAt: number; // new Date().getTime()
}

interface TodosState {
  todos: TodoState[];
}

const initialState: TodosState = { todos: [] };

const fetchRandomJoke = createAsyncThunk(
  'todos/fetchRandomJoke',
  async (arg, thunkAPI) => {
    const response = await JokeAxiosApi.getInstance().getRandomJoke();
    const { data } = response;
    if (data) {
      thunkAPI.dispatch(
        createOneTodo({
          id: v4uuid(),
          title: 'Read a joke from thunk',
          content: data.joke,
          createAt: new Date().getTime(),
        })
      );
    }
  }
);

export const todosSlice = createSlice({
  name: ' todos',
  initialState,
  reducers: {
    // reducer should be pure function so it is not suppoed to generated id
    // ideally, the id should be generated by backend
    createOneTodo: (state, action: PayloadAction<TodoState>) => {
      const newTodo = action.payload;
      newTodo.phase = TodoPhase.pending;
      state.todos = [...state.todos, newTodo];
    },
    updateOneTodo: (state, action: PayloadAction<Partial<TodoState>>) => {
      const { content, title, id } = action.payload;
      state.todos = state.todos.map((todo) => {
        if (todo.id === id) {
          todo.content = content ? content : todo.content;
          todo.title = title ? title : todo.title;
        }
        return todo;
      });
    },
    deleteOneTodo: (state, action: PayloadAction<string>) => {
      state.todos = state.todos.filter((todo) => todo.id !== action.payload);
    },
    deleteAllTodos: (state) => {
      state.todos = [];
    },
  },
  extraReducers: (builder) => {
    builder.addCase(fetchRandomJoke.fulfilled, (state, action) => {
      // no need to handle random joke since it has been created as a todo
    });
  },
});

export const { createOneTodo, deleteOneTodo, deleteAllTodos, updateOneTodo } =
  todosSlice.actions;

export const selectTodos = (state: RootState) => state.todos.todos;

export default todosSlice.reducer;

// export thunk action
export { fetchRandomJoke };
